replicaCount: 2

image:
  registry: sakibalamin
  repository: apiserver
  tag: 1.0.1
  pullPolicy: IfNotPresent
  port: 8080

labels:
  api: 1.0.1

service:
  type: NodePort
  port: 8080
  targetPort: 8080